import "@atomos_tech/katerpillar/style";
import "./globals.css";

import { Epilogue } from "next/font/google";
import type { Metadata } from "next";

import PageTransition from "./components/PageTransition";

// Load Epilogue with desired weights and subsets
const epilogue = Epilogue({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Optional: pick what you use
  style: ["normal", "italic"], // Optional
  display: "swap", // Optional: improves UX
});

export const metadata: Metadata = {
  title: "Diksha | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={epilogue.className}>
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
